### ISSUE TITLE
Problem with chest menu plugin

### ISSUE THREAD

**Issue by Jerrylum** [Jerrylum/PublicBin#13]
**Describe the bug**
Cannot open the trash bin by clicking a chest menu icon.

**To Reproduce**
1. Setup a Spigot server
2. Install plugin BetterGUI (or any other chest menu plugin)
3. Install PublicBin 1.0.1
3. Setup `plugins/BetterGUI/menu/example.yml` config file
   ```yaml
   bincmd:
     COMMAND: 'bin'
     NAME: '{rainbow}/bin'
     ID: ender_pearl
     POSITION-X: 1
     POSITION-Y: 2
   ```
4. Start the server
5. Join the server, use the command `/openmenu example.yml` to open the menu
6. Right-click the ender pearl icon

**Expected behavior**
Players should always be able to use the command `/bin` to open trash bin.

**Server (please complete the following information):**
 - Type: All Server
 - Version  All

**Workaround**
Add delay.

```yaml
bincmd:
  COMMAND: 
   - 'delay 1'
   - 'bin'
  NAME: '{rainbow}/bin'
  LORE:
    - 'It just executes /bin command'
    - 'as the player who clicked.'
  ID: ender_pearl
  POSITION-X: 1
  POSITION-Y: 2
```
